<?php
/**
 * Plugin Name:       Connection Plugin
 * Plugin URI:        https://github.com/keircatenation/rest-tests
 * GitHub Plugin URI: https://github.com/keircatenation/rest-tests
 * Description:       Code testing various aspects of WordPress's REST API.
 * Version:           1.0.1
 * Author:            Keiran Pillman
 * License:           GPL version 3 or any later version
 * License URI:       https://www.gnu.org/licenses/gpl-3.0.html
 * Text Domain:       connection
 *
 *     This plugin is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     any later version.
 *
 *     This plugin is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *     GNU General Public License for more details.
 */

if ( !defined( 'ABSPATH' ) ) {
    exit;
}
// Adding the admin page and link -- restricted to admins
add_action( 'admin_menu', 'smartsheet_token_menu' );

function smartsheet_token_menu() {
    add_menu_page(
        __( 'Smartsheet Token', 'mag-extension' ),
        __( 'Smartsheet Token', 'mag-extension' ),
        'manage_options',
        'smartsheet-token',
        'smartsheet_token_page_contents',
        'dashicons-analytics',
        3
    );
}

function smartsheet_token_page_contents() {
    ?>
        <h1>
            <?php esc_html_e( 'Smartsheet Token', 'mag-extension' ); ?>
        </h1>
        <p>The Smartsheet authorization token is generated by the Smartsheet admin (director of IT). Each token expires after a certain amount of time.</p>
        <form method="POST" action="options.php">
        <?php
            settings_fields( 'smartsheet-token' );
            do_settings_sections( 'smartsheet-token' );
            submit_button();
        ?>
        </form>
    <?php
}

// Init the settings field
add_action( 'admin_init', 'smartsheet_token_init' );
function smartsheet_token_init() {
    add_settings_section(
        'token_section',
        __( 'Smartsheet API Key', 'mag-extension' ),
        'token_callback',
        'smartsheet-token'
    );

    add_settings_field(
        'smartsheet_api_key',
        __( 'API Key', 'mag-extension' ),
        'token_markup',
        'smartsheet-token',
        'token_section'
    );
    register_setting( 'smartsheet-token', 'smartsheet_api_key' );
}
function token_callback() {
    return;
}
function token_markup() {
    $token = get_option( 'smartsheet_api_key' );
    ?>
        <label>Smartsheet API Key: <input type='text' id='smartsheet-token-input' name='smartsheet_api_key' value='<?php echo $token; ?>'></label>
    <?php
}